import { createHash } from 'node:crypto';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const schemaNames = ['action-envelope-v1', 'portfolio-event-v1', 'reasoning-output-v1'];
const schemas = Object.fromEntries(await Promise.all(schemaNames.map(async name => [name, JSON.parse(await readFile(resolve(root, 'schemas', `${name}.schema.json`), 'utf8'))])));
const stable = value => JSON.stringify(value, null, 2) + '\n';
const digest = value => createHash('sha256').update(value).digest('hex');

const jsRuntime = String.raw`
const typeOk=(value,type)=>type==='null'?value===null:type==='array'?Array.isArray(value):type==='object'?Boolean(value)&&typeof value==='object'&&!Array.isArray(value):type==='number'?typeof value==='number'&&Number.isFinite(value):typeof value===type;
const pointer=(path,key)=>path+'/'+String(key).replaceAll('~','~0').replaceAll('/','~1');
function walk(value,schema,path,errors){
  if(!schema||typeof schema!=='object')return;
  if(schema.$ref){const name=schema.$ref.replace('./','').replace('.schema.json','');return walk(value,SCHEMAS[name],path,errors);}
  if(schema.const!==undefined&&value!==schema.const)errors.push({path,code:'const',message:'must equal '+JSON.stringify(schema.const)});
  if(schema.enum&&!schema.enum.includes(value))errors.push({path,code:'enum',message:'must be one of '+schema.enum.join(', ')});
  if(schema.type){const types=Array.isArray(schema.type)?schema.type:[schema.type];if(!types.some(type=>typeOk(value,type))){errors.push({path,code:'type',message:'must be '+types.join(' or ')});return;}}
  if(typeof value==='string'){
    if(schema.minLength!==undefined&&value.length<schema.minLength)errors.push({path,code:'minLength',message:'is too short'});
    if(schema.pattern&&!new RegExp(schema.pattern).test(value))errors.push({path,code:'pattern',message:'has invalid format'});
    if(schema.format==='date-time'&&Number.isNaN(Date.parse(value)))errors.push({path,code:'format',message:'must be an ISO date-time'});
  }
  if(typeof value==='number'){
    if(schema.minimum!==undefined&&value<schema.minimum)errors.push({path,code:'minimum',message:'is below minimum'});
    if(schema.maximum!==undefined&&value>schema.maximum)errors.push({path,code:'maximum',message:'is above maximum'});
  }
  if(Array.isArray(value)&&schema.items)value.forEach((item,index)=>walk(item,schema.items,pointer(path,index),errors));
  if(value&&typeof value==='object'&&!Array.isArray(value)){
    for(const key of schema.required||[])if(!(key in value))errors.push({path:pointer(path,key),code:'required',message:'is required'});
    if(schema.additionalProperties===false)for(const key of Object.keys(value))if(!(key in (schema.properties||{})))errors.push({path:pointer(path,key),code:'additionalProperties',message:'is not allowed'});
    for(const [key,child] of Object.entries(schema.properties||{}))if(key in value)walk(value[key],child,pointer(path,key),errors);
  }
  for(const rule of schema.allOf||[]){if(!rule.if||matches(value,rule.if))walk(value,rule.then||rule,path,errors);}
  if(schema.anyOf&&!schema.anyOf.some(rule=>matches(value,rule)))errors.push({path,code:'anyOf',message:'must match at least one allowed shape'});
}
function matches(value,schema){const errors=[];walk(value,schema,'',errors);return errors.length===0;}
export function validateContract(name,value){const schema=SCHEMAS[name];if(!schema)throw new Error('Unknown portfolio contract: '+name);const errors=[];walk(value,schema,'',errors);return {valid:errors.length===0,errors};}
export function assertContract(name,value){const result=validateContract(name,value);if(!result.valid){const error=new Error(result.errors.map(x=>(x.path||'/')+' '+x.message).join('; '));error.validationErrors=result.errors;throw error;}return value;}
export const validateActionEnvelope=value=>validateContract('action-envelope-v1',value);
export const validatePortfolioEvent=value=>validateContract('portfolio-event-v1',value);
export const validateReasoningOutput=value=>validateContract('reasoning-output-v1',value);
`;

const js = `// Generated by scripts/generate.mjs. Do not edit.\nexport const CONTRACT_VERSION='1.0.0';\nexport const SCHEMAS=${JSON.stringify(schemas)};\n${jsRuntime.trim()}\n`;
const cjsRuntime=jsRuntime.replaceAll('export function','function').replaceAll('export const','const');
const cjs = `// Generated by scripts/generate.mjs. Do not edit.\nconst CONTRACT_VERSION='1.0.0';\nconst SCHEMAS=${JSON.stringify(schemas)};\n${cjsRuntime.trim()}\nmodule.exports={CONTRACT_VERSION,SCHEMAS,validateContract,assertContract,validateActionEnvelope,validatePortfolioEvent,validateReasoningOutput};\n`;
const tsTypes = `export type EvidenceLevel='E0'|'E1'|'E2'|'E3'|'E4'|'E5';\nexport type PortfolioSource='prime'|'the-portal'|'velyqua'|'game-platform'|'authority-engine';\nexport interface ActionEnvelopeV1{tenant_id:string;actor_id:string;actor_type:'user'|'reasoner'|'system'|'device'|'service';action:string;parameters:Record<string,unknown>;context:Record<string,unknown>;correlation_id:string;idempotency_key:string;schema_version:'1.0';timestamp:string}\nexport interface PortfolioEventV1{version:'1.0';event_id:string;event_type:string;source:PortfolioSource;occurred_at:string;evidence_level:EvidenceLevel;correlation_id?:string|null;subject_id?:string|null;provenance?:string[];payload:Record<string,unknown>}\nexport interface ReasoningOutputV1{kind:'recommendation'|'proposed_action'|'abstain';confidence:number;decision_summary:string;recommendation?:string|null;proposed_action?:ActionEnvelopeV1;evidence_refs?:string[];reasoner_version?:string;schema_version:'1.0'}\n`;
const ts = `// Generated by scripts/generate.mjs. Do not edit.\n// @ts-nocheck -- runtime is generated from JSON Schema; exported domain types remain strict.\n${tsTypes}export const CONTRACT_VERSION='1.0.0' as const;\nexport const SCHEMAS:Record<string,any>=${JSON.stringify(schemas)};\n${jsRuntime.replaceAll('export function','export function').replaceAll('export const','export const').trim()}\n`;
const pySchemas = JSON.stringify(schemas);
const py = `# Generated by scripts/generate.mjs. Do not edit.\nfrom __future__ import annotations\nimport datetime,json,re\nfrom typing import Any\nCONTRACT_VERSION='1.0.0'\nSCHEMAS=json.loads(${JSON.stringify(pySchemas)})\ndef _type_ok(value:Any,kind:str)->bool:\n    return (kind=='null' and value is None) or (kind=='array' and isinstance(value,list)) or (kind=='object' and isinstance(value,dict)) or (kind=='string' and isinstance(value,str)) or (kind=='number' and isinstance(value,(int,float)) and not isinstance(value,bool))\ndef _walk(value:Any,schema:dict[str,Any],path:str,errors:list[dict[str,str]])->None:\n    if '$ref' in schema:\n        name=schema['$ref'].replace('./','').replace('.schema.json','');_walk(value,SCHEMAS[name],path,errors);return\n    if 'const' in schema and value!=schema['const']: errors.append({'path':path,'code':'const','message':f\"must equal {schema['const']!r}\"})\n    if 'enum' in schema and value not in schema['enum']: errors.append({'path':path,'code':'enum','message':'has an unsupported value'})\n    if 'type' in schema:\n        kinds=schema['type'] if isinstance(schema['type'],list) else [schema['type']]\n        if not any(_type_ok(value,k) for k in kinds): errors.append({'path':path,'code':'type','message':'has an invalid type'});return\n    if isinstance(value,str):\n        if len(value)<schema.get('minLength',0): errors.append({'path':path,'code':'minLength','message':'is too short'})\n        if schema.get('pattern') and not re.match(schema['pattern'],value): errors.append({'path':path,'code':'pattern','message':'has invalid format'})\n        if schema.get('format')=='date-time':\n            try: datetime.datetime.fromisoformat(value.replace('Z','+00:00'))\n            except ValueError: errors.append({'path':path,'code':'format','message':'must be an ISO date-time'})\n    if isinstance(value,(int,float)) and not isinstance(value,bool):\n        if 'minimum' in schema and value<schema['minimum']: errors.append({'path':path,'code':'minimum','message':'is below minimum'})\n        if 'maximum' in schema and value>schema['maximum']: errors.append({'path':path,'code':'maximum','message':'is above maximum'})\n    if isinstance(value,list) and 'items' in schema:\n        for index,item in enumerate(value): _walk(item,schema['items'],f'{path}/{index}',errors)\n    if isinstance(value,dict):\n        for key in schema.get('required',[]):\n            if key not in value: errors.append({'path':f'{path}/{key}','code':'required','message':'is required'})\n        if schema.get('additionalProperties') is False:\n            for key in value:\n                if key not in schema.get('properties',{}): errors.append({'path':f'{path}/{key}','code':'additionalProperties','message':'is not allowed'})\n        for key,child in schema.get('properties',{}).items():\n            if key in value: _walk(value[key],child,f'{path}/{key}',errors)\n    for rule in schema.get('allOf',[]):\n        condition=[];_walk(value,rule.get('if',{}),path,condition)\n        if not condition: _walk(value,rule.get('then',rule),path,errors)\ndef validate_contract(name:str,value:Any)->dict[str,Any]:\n    if name not in SCHEMAS: raise ValueError(f'Unknown portfolio contract: {name}')\n    errors:list[dict[str,str]]=[];_walk(value,SCHEMAS[name],'',errors);return {'valid':not errors,'errors':errors}\ndef assert_contract(name:str,value:Any)->Any:\n    result=validate_contract(name,value)\n    if not result['valid']: raise ValueError('; '.join(f\"{e['path'] or '/'} {e['message']}\" for e in result['errors']))\n    return value\ndef validate_action_envelope(value:Any)->dict[str,Any]: return validate_contract('action-envelope-v1',value)\ndef validate_portfolio_event(value:Any)->dict[str,Any]: return validate_contract('portfolio-event-v1',value)\ndef validate_reasoning_output(value:Any)->dict[str,Any]: return validate_contract('reasoning-output-v1',value)\n`;

const outputs = {
  'generated/javascript/validators.js': js,
  'generated/javascript/validators.cjs': cjs,
  'generated/typescript/validators.ts': ts,
  'generated/python/portfolio_contracts.py': py,
};
const manifest = {contract_version:'1.0.0', schemas:Object.fromEntries(schemaNames.map(name=>[`${name}.schema.json`,digest(stable(schemas[name]))])), generated:{}};
for(const [path,content] of Object.entries(outputs))manifest.generated[path]=digest(content);
outputs['manifest.json']=stable(manifest);
let changed=false;
for(const [path,content] of Object.entries(outputs)){
  const target=resolve(root,path);let current='';try{current=await readFile(target,'utf8')}catch{}
  if(current!==content){changed=true;if(!process.argv.includes('--check')){await mkdir(dirname(target),{recursive:true});await writeFile(target,content)}}
}
if(process.argv.includes('--check')&&changed){console.error('Generated contract artifacts are stale. Run npm run generate.');process.exit(1)}
